DISCLAIMER = "This feedback was generated by a program and is not always correct. If you have any questions about the feedback please contact a TA"
LOOPS_FEEDBACK = "This function has multiple loops that look like they could be split into separate functions.\n" \
                 "These loops are at lines {0}."
MIXED_PRINT_RETURN_FEEDBACK = "This function prints the same variable that it also returns.\n" \
                              "It is often better to separate the printing of a value and the calculating of that value into separate functions."
BREAK_FEEDBACK = "This function could be split at line {0} the two resulting functions would only have:[{1}] as shared variables."
FUNCTION_TO_LONG_FEEDBACK = "This function is {0} lines long after the removal of comments, docstrings, and white space.\n" \
                            "Long function are often les readable and more likely to have errors than short functions."
GENERIC_HOW_TO_SPLIT = "When splitting functions parts of the code that are separate tasks should be separated into functions.\n" \
                       "Complex pieces of code can often become easier to read if parts of these pieces of code are separated into functions."

#COMPACT Feedback for multiple functions at once

LOOPS_COMPACT_FEEDBACK = "These functions [{0}] have multiple loops that look like they could be split into separate functions.\n" \
                         "These loops are at lines {1}."
MIXED_PRINT_RETURN_COMPACT_FEEDBACK = "These functions [{0}] print the same variable that they also return.\n" \
                              "It is often better to separate the printing of a value and the calculating of that value into separate functions.\n"
BREAK_COMPACT_FEEDBACK = "The function {0} could be split at line {1} the two resulting functions would only have:[{2}] as shared variables."
BREAK_DISCLAIMER = "This is a experimental feature the linenumber might not be correct and splitting the function is not always the best option."

FUNCTION_TO_LONG_COMPACT_FEEDBACK = "These functions [{0}] are  more than {1} lines long after the removal of comments docstrings, and white space.\n" \
                                    "Long function are often les readable and more likely to have errors than short functions."